services:
    phlexible_google_maps.staticmap:
        class: Phlexible\Bundle\GoogleMapsBundle\StaticMap

    # event listeners
    phlexible_google_maps.listener.viewframe:
        class: Phlexible\Bundle\GoogleMapsBundle\EventListener\ViewFrameListener
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.view_frame, method: onViewFrame}

    # fields
    phlexible_google_maps.field.address:
        class: Phlexible\Bundle\GoogleMapsBundle\Field\AddressField
        public: false
        tags:
            - {name: phlexible_elementtype.field, alias: address}