services:
    googlemaps.staticmap:
        class: Phlexible\GoogleMapsBundle\StaticMap

    # asset providers
    googlemaps.asset.scripts:
        class: Phlexible\GoogleMapsBundle\AssetProvider\GoogleMapsAssetProvider
        arguments: [@file_locator]
        tags:
            - {name: "asset.provider", priority: -500}

    # dwoo plugins
    googlemaps.dwoo.plugin.staticmap:
        class: Phlexible\GoogleMapsBundle\Plugin\StaticGoogleMap
        tags:
            - {name: "dwoo.plugin", alias: mwStaticGoogleMaps}

    # event listeners
    googlemaps.listener.rendererassign:
        class: Phlexible\GoogleMapsBundle\EventListener\RendererAssignListener
        arguments: ["%googlemaps.api_key%"]
        tags:
            - {name: "kernel.event_listener", event: renderers.assign, method: onRendererAssign}

    googlemaps.listener.viewframe:
        class: Phlexible\GoogleMapsBundle\EventListener\ViewFrameListener
        tags:
            - {name: "kernel.event_listener", event: gui.view_frame, method: onViewFrame}

    # fields
    googlemaps.field.address:
        class: Phlexible\GoogleMapsBundle\Field\AddressField
        tags:
            - {name: "elementtypes.field", alias: address}