services:
    googlemaps.staticmap:
        class: Phlexible\GoogleMapsComponent\StaticMap

    # dwoo plugins
    googlemaps.dwoo.plugin.staticmap:
        class: Phlexible\GoogleMapsComponent\Plugin\StaticGoogleMap
        tags:
            - {name: "dwoo.plugin", alias: mwStaticGoogleMaps}

    # event listeners
    googlemaps.listener.rendererassign:
        class: Phlexible\GoogleMapsComponent\EventListener\RendererAssignListener
        arguments: ["%googlemaps.api_key%"]
        tags:
            - {name: "kernel.event_listener", event: renderers.assign, method: onRendererAssign}

    googlemaps.listener.viewframe:
        class: Phlexible\GoogleMapsComponent\EventListener\ViewFrameListener
        tags:
            - {name: "kernel.event_listener", event: gui.view_frame, method: onViewFrame}

    # assets
    googlemaps.asset.scripts:
        class: Phlexible\GoogleMapsComponent\Asset\ScriptCollection
        arguments: ["%googlemaps.asset.script_path%"]
        tags:
            - {name: "asset.script", priority: -500}

    # fields
    googlemaps.field.address:
        class: Phlexible\GoogleMapsComponent\Field\AddressField
        tags:
            - {name: "elementtypes.field", alias: address}