tags:
    - ["asset.translation", {page: googlemaps, namespace: "Makeweb.strings.Googlemaps"}]

services:
    googlemapsStatic:
        class: Phlexible\GoogleMapsComponent\StaticMap

    # dwoo plugins
    googlemapsPluginStatisGoogleMap:
        class: Phlexible\GoogleMapsComponent\Plugin\StaticGoogleMap
        tags:
            - ["dwoo.plugin", {alias: mwStaticGoogleMaps}]

    # listeners
    googlemapsListenerRendererAssign:
        class: Phlexible\GoogleMapsComponent\Listener\RendererAssignListener
        arguments: ["%googlemaps.api_key%"]
        tags:
            - ["event.listener", {event: renderers.assign, method: onRendererAssign}]
    googlemapsListenerViewFrame:
        class: Phlexible\GoogleMapsComponent\Listener\ViewFrameListener
        tags:
            - ["event.listener", {event: frame.view_frame, method: onViewFrame}]

    # assets
    googlemapsAssetScripts:
        class: Phlexible\GoogleMapsComponent\Asset\ScriptCollection
        arguments: ["%googlemaps.asset.script_path%"]
        tags:
            - ["asset.script", {priority: -500}]